# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
          cache: maven

      - name: Build with Maven
        run: mvn -B verify --file pom.xml

      - name: Configure Git user for maven release plugin
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Publish to GitHub Packages Apache Maven
        run: mvn -B release:prepare release:perform -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: checkout tag
        run: git checkout HEAD^

      - name: get tagname
        id: taginfo
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      - name: Update CHANGELOG
        id: changelog
        uses: Requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.taginfo.outputs.tag }}
          writeToFile: false

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          name: ${{ github.taginfo.outputs.tag }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}
